# Generated by Django 3.1.4 on 2020-12-05 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('PriceTracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urls',
            name='exp_price',
            field=models.TextField(default=1),
        ),
    ]
