# Generated by Django 3.1.4 on 2020-12-05 13:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('PriceTracker', '0004_auto_20201205_1915'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Urls',
            new_name='UrlsToTrack',
        ),
    ]
