# Generated by Django 3.1.4 on 2020-12-05 13:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('PriceTracker', '0005_auto_20201205_1920'),
    ]

    operations = [
        migrations.CreateModel(
            name='Urls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('url', models.TextField()),
                ('exp_price', models.TextField(default=100)),
            ],
        ),
    ]
