# Generated by Django 3.1.4 on 2020-12-05 13:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('PriceTracker', '0006_urls'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Urls',
        ),
    ]
