# Generated by Django 3.1.4 on 2021-01-03 10:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('PriceTracker', '0007_delete_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlstotrack',
            name='email',
            field=models.TextField(default='vineelsai26@gmail.com'),
        ),
    ]
